name: Emerge Size Analysis
on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'feature/*'

jobs:
  emerge_size_analysis_automation:
    runs-on: ubuntu-latest
    steps:
      - name: authenticate with GitHub
        run: |
          git config --global user.email "sha.sdk_deployment@sendbird.com"
          git config --global user.name "sha.sdk_deployment"
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/checkout@v3
        with:
          ref : 'develop'
      - name: Emerge size analysis
        run: ./gradlew :app:emergeUploadDebugApk
        env:
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_KEY }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
          PR_BASE_SHA: '321ee8663fefeae058f00f295a757f22718e67aa'
